"""Bundle game data (rubric + persona library + prompts) into cloudflare/gamedata.js
so the Worker's /turn endpoint is self-contained. Run after editing personas/prompts:
    python cloudflare/build_gamedata.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
rubric = json.loads((ROOT / "data" / "judge_rubric.json").read_text(encoding="utf-8"))
personas = {}
for p in sorted((ROOT / "data" / "persona_library").glob("*.json")):
    d = json.loads(p.read_text(encoding="utf-8"))
    personas[d["persona_id"]] = d
student_prompt = (ROOT / "tools" / "student_prompt.txt").read_text(encoding="utf-8")
coach_prompt = (ROOT / "tools" / "coach_prompt.txt").read_text(encoding="utf-8")


def tmpl(s: str) -> str:
    return "`" + s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${") + "`"


out = "// AUTO-GENERATED by build_gamedata.py — do not edit by hand.\n"
out += "export const RUBRIC = " + json.dumps(rubric) + ";\n"
out += "export const PERSONAS = " + json.dumps(personas, ensure_ascii=False) + ";\n"
out += "export const STUDENT_PROMPT = " + tmpl(student_prompt) + ";\n"
out += "export const COACH_PROMPT = " + tmpl(coach_prompt) + ";\n"
(ROOT / "cloudflare" / "gamedata.js").write_text(out, encoding="utf-8")
print("wrote cloudflare/gamedata.js (%d personas, %d bytes)" % (len(personas), len(out)))
